-- Migration: Insert Mock Jobs Data
-- This script inserts the corrected mock job data into the jobs table

-- Clear existing data
DELETE FROM jobs;

-- Insert mock jobs data
INSERT INTO jobs (
    id, title, company, company_id, company_logo_url, location, type, experience_level, 
    remote_option, salary, description, requirements, responsibilities, benefits, tags,
    posted_at, application_deadline, applicants, featured, active, created_at, updated_at
) VALUES 
-- Job 1: Senior Full Stack Developer
(
    '123e4567-e89b-12d3-a456-426614174000',
    'Senior Full Stack Developer',
    'TechCorp Solutions',
    'comp-001',
    'https://via.placeholder.com/200x80/4A90E2/FFFFFF?text=TechCorp',
    'San Francisco, CA',
    'full-time',
    'senior',
    'hybrid',
    '{"min": 150000, "max": 200000, "currency": "USD", "period": "yearly"}',
    'We are looking for a Senior Full Stack Developer to join our growing engineering team. You will be responsible for designing and implementing scalable web applications using modern technologies.

    As a senior member of the team, you''ll mentor junior developers, participate in architectural decisions, and help shape our engineering culture.',
    ARRAY['5+ years of experience in full-stack development', 'Strong proficiency in React, Node.js, and TypeScript', 'Experience with cloud platforms (AWS preferred)', 'Solid understanding of database design and optimization', 'Experience with microservices architecture', 'Excellent communication and leadership skills'],
    ARRAY['Design and develop scalable web applications', 'Lead technical projects from conception to deployment', 'Mentor junior developers and conduct code reviews', 'Collaborate with product managers and designers', 'Participate in on-call rotation for production support', 'Contribute to architectural decisions and technical strategy'],
    ARRAY['Competitive salary and equity', 'Comprehensive health, dental, and vision insurance', 'Unlimited PTO policy', '401(k) with company matching', 'Professional development budget', 'Flexible work arrangements'],
    ARRAY['React', 'Node.js', 'TypeScript', 'AWS', 'Full Stack'],
    '2025-01-15T00:00:00.000Z'::timestamp with time zone,
    '2025-02-28T00:00:00.000Z'::timestamp with time zone,
    42,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 2: Frontend Engineer
(
    '234f5678-f9ac-23e4-b567-537725285111',
    'Frontend Engineer',
    'StartupHub',
    'comp-002',
    'https://via.placeholder.com/200x80/28A745/FFFFFF?text=StartupHub',
    'New York, NY',
    'full-time',
    'mid',
    'remote',
    '{"min": 100000, "max": 140000, "currency": "USD", "period": "yearly"}',
    'Join our dynamic team as a Frontend Engineer and help build the future of digital payments. You''ll work on cutting-edge fintech products used by millions of users worldwide.',
    ARRAY['3+ years of experience in frontend development', 'Expert knowledge of React and React Native', 'Strong understanding of JavaScript/TypeScript', 'Experience with state management (Redux, MobX, or similar)', 'Knowledge of responsive design and cross-browser compatibility', 'Passion for creating exceptional user experiences'],
    ARRAY['Build and maintain responsive web applications', 'Collaborate with designers to implement pixel-perfect UIs', 'Optimize applications for maximum speed and scalability', 'Write clean, maintainable, and testable code', 'Participate in agile development processes'],
    ARRAY['Competitive salary with equity', 'Health, dental, and vision insurance', 'Flexible working hours', 'Remote-first culture', 'Learning and development stipend'],
    ARRAY['React', 'React Native', 'TypeScript', 'Fintech', 'Remote'],
    '2025-01-20T00:00:00.000Z'::timestamp with time zone,
    '2025-03-20T00:00:00.000Z'::timestamp with time zone,
    28,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 3: DevOps Engineer
(
    '34567890-1234-5678-9abc-def012345678',
    'DevOps Engineer',
    'Global Health Systems',
    'comp-003',
    'https://via.placeholder.com/200x80/DC3545/FFFFFF?text=GlobalHealth',
    'Boston, MA',
    'full-time',
    'senior',
    'hybrid',
    '{"min": 130000, "max": 170000, "currency": "USD", "period": "yearly"}',
    'We''re seeking a DevOps Engineer to help us scale our healthcare platform. You''ll work on critical infrastructure that powers applications used by healthcare providers nationwide.',
    ARRAY['5+ years of DevOps/SRE experience', 'Strong experience with AWS and cloud architecture', 'Proficiency in Infrastructure as Code (Terraform, CloudFormation)', 'Experience with container orchestration (Kubernetes)', 'Knowledge of CI/CD pipelines and automation', 'Understanding of HIPAA compliance and security best practices'],
    ARRAY['Design and maintain scalable cloud infrastructure', 'Implement and manage CI/CD pipelines', 'Monitor system performance and ensure high availability', 'Automate deployment and operational processes', 'Ensure security and compliance standards are met', 'Collaborate with development teams to improve deployment processes'],
    ARRAY['Competitive compensation', 'Excellent health coverage', '4 weeks PTO', 'Parental leave policy', 'Professional development opportunities', 'Mission-driven work environment'],
    ARRAY['AWS', 'Kubernetes', 'Terraform', 'DevOps', 'Healthcare'],
    '2025-01-18T00:00:00.000Z'::timestamp with time zone,
    '2025-03-18T00:00:00.000Z'::timestamp with time zone,
    15,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 4: Junior Backend Developer
(
    '45678901-2345-6789-abcd-ef0123456789',
    'Junior Backend Developer',
    'TechCorp Solutions',
    'comp-001',
    'https://via.placeholder.com/200x80/4A90E2/FFFFFF?text=TechCorp',
    'Austin, TX',
    'full-time',
    'entry',
    'on-site',
    '{"min": 70000, "max": 90000, "currency": "USD", "period": "yearly"}',
    'Start your career with TechCorp as a Junior Backend Developer. This is an excellent opportunity for recent graduates or early-career developers to learn from experienced engineers and work on impactful projects.',
    ARRAY['Bachelor''s degree in Computer Science or related field', 'Understanding of programming fundamentals', 'Knowledge of at least one backend language (Python, Java, or Node.js)', 'Familiarity with databases and SQL', 'Strong problem-solving skills', 'Eagerness to learn and grow'],
    ARRAY['Assist in developing and maintaining backend services', 'Write unit tests and documentation', 'Participate in code reviews and team meetings', 'Learn and apply best practices in software development', 'Collaborate with senior developers on feature implementation'],
    ARRAY['Competitive entry-level salary', 'Comprehensive benefits package', 'Mentorship program', 'Education reimbursement', 'Clear career progression path', 'Modern office with free meals'],
    ARRAY['Python', 'Node.js', 'Entry Level', 'Backend'],
    '2025-01-22T00:00:00.000Z'::timestamp with time zone,
    '2025-03-22T00:00:00.000Z'::timestamp with time zone,
    89,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 5: Product Designer
(
    '56789012-3456-7890-bcde-f01234567890',
    'Product Designer',
    'StartupHub',
    'comp-002',
    'https://via.placeholder.com/200x80/28A745/FFFFFF?text=StartupHub',
    'Remote',
    'full-time',
    'mid',
    'remote',
    '{"min": 90000, "max": 130000, "currency": "USD", "period": "yearly"}',
    'We''re looking for a talented Product Designer to shape the user experience of our fintech products. You''ll work closely with product managers and engineers to create intuitive, beautiful interfaces.',
    ARRAY['3+ years of product design experience', 'Strong portfolio demonstrating UI/UX skills', 'Proficiency in Figma or similar design tools', 'Understanding of design systems and component libraries', 'Experience with user research and testing', 'Excellent communication and presentation skills'],
    ARRAY['Design user interfaces for web and mobile applications', 'Create and maintain design systems', 'Conduct user research and usability testing', 'Collaborate with cross-functional teams', 'Present design concepts to stakeholders', 'Iterate on designs based on feedback and data'],
    ARRAY['Remote work from anywhere', 'Competitive compensation', 'Health insurance stipend', 'Home office setup budget', 'Annual company retreats', 'Equity compensation'],
    ARRAY['UI/UX', 'Product Design', 'Figma', 'Remote', 'Fintech'],
    '2025-01-19T00:00:00.000Z'::timestamp with time zone,
    '2025-03-19T00:00:00.000Z'::timestamp with time zone,
    56,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 6: Backend Engineer
(
    '67890123-4567-8901-cdef-012345678901',
    'Backend Engineer',
    'TechCorp Solutions',
    'comp-001',
    'https://via.placeholder.com/200x80/4A90E2/FFFFFF?text=TechCorp',
    'Austin, TX',
    'full-time',
    'senior',
    'on-site',
    '{"min": 140000, "max": 180000, "currency": "USD", "period": "yearly"}',
    'Join our backend team to build scalable microservices and APIs that power our enterprise applications.',
    ARRAY['5+ years of backend development experience', 'Expert in Python or Java', 'Experience with microservices architecture', 'Strong knowledge of databases and caching', 'Experience with message queues and event-driven systems'],
    ARRAY['Design and implement RESTful APIs', 'Build scalable microservices', 'Optimize database queries and system performance', 'Implement security best practices', 'Collaborate with frontend and DevOps teams'],
    ARRAY['Competitive salary and equity', 'Health insurance', '401(k) matching', 'Relocation assistance', 'Professional development budget'],
    ARRAY['Python', 'Java', 'Microservices', 'AWS', 'Backend'],
    '2025-01-20T00:00:00.000Z'::timestamp with time zone,
    '2025-03-20T00:00:00.000Z'::timestamp with time zone,
    38,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 7: Product Manager
(
    '78901234-5678-9012-def0-123456789012',
    'Product Manager',
    'InnovateTech',
    'comp-004',
    'https://via.placeholder.com/200x80/FFC107/FFFFFF?text=InnovateTech',
    'Seattle, WA',
    'full-time',
    'mid',
    'hybrid',
    '{"min": 120000, "max": 160000, "currency": "USD", "period": "yearly"}',
    'Lead product development for our AI-powered analytics platform.',
    ARRAY['3+ years of product management experience', 'Experience with B2B SaaS products', 'Strong analytical and problem-solving skills', 'Excellent communication skills', 'Technical background preferred'],
    ARRAY['Define product vision and strategy', 'Work closely with engineering and design teams', 'Conduct user research and gather feedback', 'Prioritize features and manage roadmap', 'Track product metrics and KPIs'],
    ARRAY['Competitive compensation', 'Stock options', 'Flexible work schedule', 'Health and wellness benefits', 'Learning stipend'],
    ARRAY['Product Management', 'B2B', 'SaaS', 'Analytics', 'AI'],
    '2025-01-21T00:00:00.000Z'::timestamp with time zone,
    '2025-03-21T00:00:00.000Z'::timestamp with time zone,
    45,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 8: DevOps Engineer
(
    '89012345-6789-0123-ef01-234567890123',
    'DevOps Engineer',
    'CloudScale',
    'comp-005',
    'https://via.placeholder.com/200x80/17A2B8/FFFFFF?text=CloudScale',
    'Denver, CO',
    'full-time',
    'senior',
    'remote',
    '{"min": 135000, "max": 175000, "currency": "USD", "period": "yearly"}',
    'Help us build and maintain world-class cloud infrastructure.',
    ARRAY['5+ years of DevOps experience', 'Expert in Kubernetes and Docker', 'Strong knowledge of AWS or GCP', 'Experience with Infrastructure as Code', 'Proficient in scripting (Python, Bash)'],
    ARRAY['Design and implement CI/CD pipelines', 'Manage Kubernetes clusters', 'Implement monitoring and alerting', 'Automate infrastructure provisioning', 'Ensure security and compliance'],
    ARRAY['Remote-first culture', 'Competitive salary', 'Equity package', 'Health insurance', 'Conference budget'],
    ARRAY['DevOps', 'Kubernetes', 'AWS', 'Docker', 'CI/CD'],
    '2025-01-22T00:00:00.000Z'::timestamp with time zone,
    '2025-03-22T00:00:00.000Z'::timestamp with time zone,
    52,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 9: Data Scientist
(
    '90123456-7890-1234-f012-345678901234',
    'Data Scientist',
    'DataInsights',
    'comp-006',
    'https://via.placeholder.com/200x80/6F42C1/FFFFFF?text=DataInsights',
    'Boston, MA',
    'full-time',
    'mid',
    'hybrid',
    '{"min": 110000, "max": 150000, "currency": "USD", "period": "yearly"}',
    'Join our data science team to build ML models and derive insights from large datasets.',
    ARRAY['3+ years of data science experience', 'Strong knowledge of Python and R', 'Experience with machine learning frameworks', 'Proficient in SQL and data visualization', 'MS in Computer Science or related field'],
    ARRAY['Build and deploy machine learning models', 'Analyze large datasets for insights', 'Create data visualizations and reports', 'Collaborate with product teams', 'Present findings to stakeholders'],
    ARRAY['Competitive salary', 'Flexible work arrangements', 'Health benefits', 'Professional development', 'Stock options'],
    ARRAY['Data Science', 'Machine Learning', 'Python', 'R', 'SQL'],
    '2025-01-18T00:00:00.000Z'::timestamp with time zone,
    '2025-03-18T00:00:00.000Z'::timestamp with time zone,
    67,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 10: QA Engineer
(
    '01234567-8901-2345-0123-456789012345',
    'QA Engineer',
    'TechCorp Solutions',
    'comp-001',
    'https://via.placeholder.com/200x80/4A90E2/FFFFFF?text=TechCorp',
    'Portland, OR',
    'full-time',
    'entry',
    'on-site',
    '{"min": 70000, "max": 90000, "currency": "USD", "period": "yearly"}',
    'Start your career in QA with our experienced team.',
    ARRAY['1+ years of QA experience', 'Knowledge of testing methodologies', 'Basic programming skills', 'Attention to detail', 'Good communication skills'],
    ARRAY['Write and execute test cases', 'Report and track bugs', 'Perform regression testing', 'Collaborate with developers', 'Improve testing processes'],
    ARRAY['Mentorship program', 'Health insurance', 'PTO', 'Career growth opportunities', 'Team events'],
    ARRAY['QA', 'Testing', 'Quality Assurance', 'Junior', 'Entry Level'],
    '2025-01-19T00:00:00.000Z'::timestamp with time zone,
    '2025-03-19T00:00:00.000Z'::timestamp with time zone,
    28,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 11: Mobile Developer
(
    '12345678-9012-3456-1234-567890123456',
    'Mobile Developer',
    'StartupHub',
    'comp-002',
    'https://via.placeholder.com/200x80/28A745/FFFFFF?text=StartupHub',
    'San Francisco, CA',
    'full-time',
    'mid',
    'remote',
    '{"min": 105000, "max": 145000, "currency": "USD", "period": "yearly"}',
    'Build innovative mobile apps for iOS and Android platforms.',
    ARRAY['3+ years of mobile development', 'Experience with React Native or Flutter', 'Knowledge of iOS and Android platforms', 'Understanding of mobile UI/UX', 'App Store deployment experience'],
    ARRAY['Develop cross-platform mobile apps', 'Implement responsive UI designs', 'Optimize app performance', 'Integrate with backend APIs', 'Maintain app store listings'],
    ARRAY['Remote work', 'Equity compensation', 'Health benefits', 'Equipment budget', 'Flexible hours'],
    ARRAY['Mobile', 'React Native', 'Flutter', 'iOS', 'Android'],
    '2025-01-20T00:00:00.000Z'::timestamp with time zone,
    '2025-03-20T00:00:00.000Z'::timestamp with time zone,
    41,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 12: Security Engineer
(
    '23456789-0123-4567-2345-678901234567',
    'Security Engineer',
    'SecureNet',
    'comp-007',
    'https://via.placeholder.com/200x80/FD7E14/FFFFFF?text=SecureNet',
    'Washington, DC',
    'full-time',
    'senior',
    'hybrid',
    '{"min": 145000, "max": 185000, "currency": "USD", "period": "yearly"}',
    'Lead security initiatives for our enterprise clients.',
    ARRAY['5+ years of security experience', 'Security certifications (CISSP, CEH)', 'Experience with penetration testing', 'Knowledge of compliance frameworks', 'Strong analytical skills'],
    ARRAY['Conduct security assessments', 'Implement security controls', 'Respond to security incidents', 'Develop security policies', 'Train team on security practices'],
    ARRAY['High compensation', 'Security clearance sponsorship', 'Professional certifications', 'Health and dental', 'Retirement plan'],
    ARRAY['Security', 'Cybersecurity', 'CISSP', 'Penetration Testing', 'Compliance'],
    '2025-01-17T00:00:00.000Z'::timestamp with time zone,
    '2025-03-17T00:00:00.000Z'::timestamp with time zone,
    33,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 13: Technical Writer
(
    '34567890-1234-5678-3456-789012345678',
    'Technical Writer',
    'TechCorp Solutions',
    'comp-001',
    'https://via.placeholder.com/200x80/4A90E2/FFFFFF?text=TechCorp',
    'Remote',
    'full-time',
    'mid',
    'remote',
    '{"min": 85000, "max": 115000, "currency": "USD", "period": "yearly"}',
    'Create clear and comprehensive technical documentation.',
    ARRAY['3+ years of technical writing', 'Experience with developer documentation', 'Understanding of APIs and SDKs', 'Excellent writing skills', 'Basic programming knowledge'],
    ARRAY['Write API documentation', 'Create user guides and tutorials', 'Maintain documentation standards', 'Work with engineering teams', 'Review and edit content'],
    ARRAY['Fully remote', 'Flexible schedule', 'Health insurance', 'Professional development', 'Equipment allowance'],
    ARRAY['Technical Writing', 'Documentation', 'Remote', 'APIs', 'Content'],
    '2025-01-21T00:00:00.000Z'::timestamp with time zone,
    '2025-03-21T00:00:00.000Z'::timestamp with time zone,
    24,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 14: Cloud Architect
(
    '45678901-2345-6789-4567-890123456789',
    'Cloud Architect',
    'CloudScale',
    'comp-005',
    'https://via.placeholder.com/200x80/17A2B8/FFFFFF?text=CloudScale',
    'Chicago, IL',
    'full-time',
    'senior',
    'hybrid',
    '{"min": 155000, "max": 195000, "currency": "USD", "period": "yearly"}',
    'Design and implement cloud solutions for enterprise clients.',
    ARRAY['7+ years of cloud architecture experience', 'AWS or Azure certifications', 'Experience with large-scale systems', 'Strong leadership skills', 'Enterprise architecture knowledge'],
    ARRAY['Design cloud architectures', 'Lead migration projects', 'Define best practices', 'Mentor engineering teams', 'Client consultations'],
    ARRAY['Top-tier compensation', 'Stock options', 'Executive health plan', 'Annual bonus', 'Conference speaking opportunities'],
    ARRAY['Cloud', 'Architecture', 'AWS', 'Azure', 'Enterprise'],
    '2025-01-16T00:00:00.000Z'::timestamp with time zone,
    '2025-03-16T00:00:00.000Z'::timestamp with time zone,
    29,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 15: Marketing Manager
(
    '56789012-3456-7890-5678-901234567890',
    'Marketing Manager',
    'StartupHub',
    'comp-002',
    'https://via.placeholder.com/200x80/28A745/FFFFFF?text=StartupHub',
    'Miami, FL',
    'full-time',
    'mid',
    'hybrid',
    '{"min": 95000, "max": 125000, "currency": "USD", "period": "yearly"}',
    'Lead our marketing efforts to drive growth and brand awareness.',
    ARRAY['4+ years of marketing experience', 'Experience with digital marketing', 'Strong analytical skills', 'Creative mindset', 'Team leadership experience'],
    ARRAY['Develop marketing strategies', 'Manage marketing campaigns', 'Analyze marketing metrics', 'Lead marketing team', 'Collaborate with sales'],
    ARRAY['Competitive salary', 'Performance bonus', 'Health benefits', 'Creative freedom', 'Growth opportunities'],
    ARRAY['Marketing', 'Digital Marketing', 'Strategy', 'Leadership', 'Growth'],
    '2025-01-18T00:00:00.000Z'::timestamp with time zone,
    '2025-03-18T00:00:00.000Z'::timestamp with time zone,
    58,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 16: Frontend Developer
(
    '67890123-4567-8901-6789-012345678901',
    'Frontend Developer',
    'InnovateTech',
    'comp-004',
    'https://via.placeholder.com/200x80/FFC107/FFFFFF?text=InnovateTech',
    'Phoenix, AZ',
    'full-time',
    'entry',
    'on-site',
    '{"min": 65000, "max": 85000, "currency": "USD", "period": "yearly"}',
    'Join our frontend team as a junior developer and grow your skills.',
    ARRAY['1+ years of frontend experience', 'Knowledge of React or Vue', 'HTML, CSS, JavaScript skills', 'Eager to learn', 'Team player'],
    ARRAY['Build user interfaces', 'Implement designs', 'Write clean code', 'Fix bugs', 'Learn from senior developers'],
    ARRAY['Mentorship program', 'Learning budget', 'Health insurance', 'Gym membership', 'Team lunches'],
    ARRAY['Frontend', 'React', 'Junior', 'JavaScript', 'Entry Level'],
    '2025-01-19T00:00:00.000Z'::timestamp with time zone,
    '2025-03-19T00:00:00.000Z'::timestamp with time zone,
    72,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 17: Data Engineer
(
    '78901234-5678-9012-7890-123456789012',
    'Data Engineer',
    'DataInsights',
    'comp-006',
    'https://via.placeholder.com/200x80/6F42C1/FFFFFF?text=DataInsights',
    'Atlanta, GA',
    'full-time',
    'senior',
    'remote',
    '{"min": 130000, "max": 170000, "currency": "USD", "period": "yearly"}',
    'Build and maintain data pipelines for our analytics platform.',
    ARRAY['5+ years of data engineering', 'Experience with Apache Spark', 'Strong SQL and Python skills', 'Cloud platform experience', 'ETL/ELT expertise'],
    ARRAY['Design data pipelines', 'Optimize data processing', 'Maintain data quality', 'Build data infrastructure', 'Support data scientists'],
    ARRAY['Remote work', 'Competitive pay', 'Stock options', 'Healthcare', 'Parental leave'],
    ARRAY['Data Engineering', 'Spark', 'Python', 'SQL', 'ETL'],
    '2025-01-20T00:00:00.000Z'::timestamp with time zone,
    '2025-03-20T00:00:00.000Z'::timestamp with time zone,
    44,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 18: Sales Engineer
(
    '89012345-6789-0123-8901-234567890123',
    'Sales Engineer',
    'TechCorp Solutions',
    'comp-001',
    'https://via.placeholder.com/200x80/4A90E2/FFFFFF?text=TechCorp',
    'Dallas, TX',
    'full-time',
    'mid',
    'hybrid',
    '{"min": 100000, "max": 140000, "currency": "USD", "period": "yearly"}',
    'Bridge the gap between sales and engineering teams.',
    ARRAY['3+ years technical sales experience', 'Engineering background', 'Excellent presentation skills', 'Customer-focused mindset', 'Travel flexibility'],
    ARRAY['Conduct technical demos', 'Support sales team', 'Understand customer needs', 'Provide technical solutions', 'Build customer relationships'],
    ARRAY['Base + commission', 'Travel expenses', 'Health benefits', 'Car allowance', 'Sales incentives'],
    ARRAY['Sales', 'Engineering', 'Technical Sales', 'B2B', 'SaaS'],
    '2025-01-21T00:00:00.000Z'::timestamp with time zone,
    '2025-03-21T00:00:00.000Z'::timestamp with time zone,
    31,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 19: AI/ML Engineer
(
    '90123456-7890-1234-9012-345678901234',
    'AI/ML Engineer',
    'InnovateTech',
    'comp-004',
    'https://via.placeholder.com/200x80/FFC107/FFFFFF?text=InnovateTech',
    'San Francisco, CA',
    'full-time',
    'senior',
    'hybrid',
    '{"min": 150000, "max": 190000, "currency": "USD", "period": "yearly"}',
    'Lead AI/ML initiatives for our next-generation products.',
    ARRAY['5+ years ML experience', 'PhD or MS in Computer Science', 'Deep learning expertise', 'Published research preferred', 'Production ML experience'],
    ARRAY['Design ML systems', 'Train and deploy models', 'Research new techniques', 'Mentor junior engineers', 'Present to stakeholders'],
    ARRAY['Top compensation', 'Research budget', 'Conference attendance', 'Stock options', 'Sabbatical option'],
    ARRAY['AI', 'Machine Learning', 'Deep Learning', 'Python', 'Research'],
    '2025-01-22T00:00:00.000Z'::timestamp with time zone,
    '2025-03-22T00:00:00.000Z'::timestamp with time zone,
    27,
    true,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 20: HR Manager
(
    'a1234567-8901-2345-0123-456789012345',
    'HR Manager',
    'GlobalHealth',
    'comp-008',
    'https://via.placeholder.com/200x80/DC3545/FFFFFF?text=GlobalHealth',
    'Nashville, TN',
    'full-time',
    'mid',
    'on-site',
    '{"min": 80000, "max": 110000, "currency": "USD", "period": "yearly"}',
    'Lead HR initiatives for our growing healthcare organization.',
    ARRAY['4+ years HR experience', 'SHRM certification preferred', 'Healthcare industry knowledge', 'Strong interpersonal skills', 'Employment law knowledge'],
    ARRAY['Manage HR operations', 'Recruit and onboard', 'Handle employee relations', 'Develop HR policies', 'Ensure compliance'],
    ARRAY['Healthcare benefits', 'Professional development', 'Work-life balance', 'Retirement plan', 'Employee assistance program'],
    ARRAY['HR', 'Human Resources', 'Healthcare', 'Management', 'SHRM'],
    '2025-01-19T00:00:00.000Z'::timestamp with time zone,
    '2025-03-19T00:00:00.000Z'::timestamp with time zone,
    36,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 21: Systems Administrator
(
    'b1234567-8901-2345-0123-456789012345',
    'Systems Administrator',
    'TechCorp Solutions',
    'comp-001',
    'https://via.placeholder.com/200x80/4A90E2/FFFFFF?text=TechCorp',
    'San Francisco, CA',
    'full-time',
    'mid',
    'hybrid',
    '{"min": 90000, "max": 120000, "currency": "USD", "period": "yearly"}',
    'Manage and maintain our IT infrastructure.',
    ARRAY['3+ years of sysadmin experience', 'Linux and Windows expertise', 'Networking knowledge', 'Security best practices', 'Problem-solving skills'],
    ARRAY['Manage servers and networks', 'Implement security policies', 'Monitor system performance', 'Handle user support', 'Document procedures'],
    ARRAY['Health insurance', 'PTO', '401(k)', 'Training budget', 'On-call compensation'],
    ARRAY['SysAdmin', 'Linux', 'Windows', 'Networking', 'IT'],
    '2025-01-23T00:00:00.000Z'::timestamp with time zone,
    '2025-03-23T00:00:00.000Z'::timestamp with time zone,
    19,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 22: Database Administrator
(
    'c1234567-8901-2345-0123-456789012345',
    'Database Administrator',
    'DataInsights',
    'comp-006',
    'https://via.placeholder.com/200x80/6F42C1/FFFFFF?text=DataInsights',
    'Remote',
    'full-time',
    'senior',
    'remote',
    '{"min": 120000, "max": 160000, "currency": "USD", "period": "yearly"}',
    'Manage and optimize our database infrastructure.',
    ARRAY['5+ years DBA experience', 'PostgreSQL and MySQL expertise', 'Performance tuning skills', 'Backup and recovery', 'High availability setup'],
    ARRAY['Database administration', 'Performance optimization', 'Backup strategies', 'Security implementation', 'Monitoring and alerts'],
    ARRAY['Remote work', 'Competitive salary', 'Stock options', 'Healthcare', 'Learning budget'],
    ARRAY['DBA', 'PostgreSQL', 'MySQL', 'Database', 'Remote'],
    '2025-01-24T00:00:00.000Z'::timestamp with time zone,
    '2025-03-24T00:00:00.000Z'::timestamp with time zone,
    15,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),

-- Job 23: Junior Developer
(
    'd1234567-8901-2345-0123-456789012345',
    'Junior Developer',
    'StartupHub',
    'comp-002',
    'https://via.placeholder.com/200x80/28A745/FFFFFF?text=StartupHub',
    'New York, NY',
    'full-time',
    'entry',
    'hybrid',
    '{"min": 60000, "max": 80000, "currency": "USD", "period": "yearly"}',
    'Start your development career with our mentorship program.',
    ARRAY['CS degree or bootcamp', 'Basic programming skills', 'Eager to learn', 'Good communication', 'Team player'],
    ARRAY['Write clean code', 'Learn from seniors', 'Fix bugs', 'Write tests', 'Participate in reviews'],
    ARRAY['Mentorship program', 'Health insurance', 'Learning budget', 'Flexible hours', 'Career growth'],
    ARRAY['Junior', 'Entry Level', 'JavaScript', 'React', 'Node.js'],
    '2025-01-25T00:00:00.000Z'::timestamp with time zone,
    '2025-03-25T00:00:00.000Z'::timestamp with time zone,
    89,
    false,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

-- Log successful insertion
DO $$
BEGIN
    RAISE NOTICE 'Successfully inserted 23 mock jobs into the jobs table';
END $$; 