name: Trigger auto deployment for jairojobs2025

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/jairojobs2025-AutoDeployTrigger-398edc90-fe02-42da-988b-e85d02cd395b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.JAIROJOBS2025_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.JAIROJOBS2025_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.JAIROJOBS2025_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: jairo.azurecr.io
          registryUsername: ${{ secrets.JAIROJOBS2025_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JAIROJOBS2025_REGISTRY_PASSWORD }}
          containerAppName: jairojobs2025
          resourceGroup: jairojobs2025
          imageToBuild: jairo.azurecr.io/jairojobs2025:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


